window.StepStyle = (() => {
  const KEYS={cart:"stepstyle_cart",wishlist:"stepstyle_wishlist",users:"stepstyle_users",session:"stepstyle_session",orders:"stepstyle_orders",lastOrder:"stepstyle_last_order"};
  const icons={search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8Z"/></svg>',bag:'<svg viewBox="0 0 24 24"><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></svg>',menu:'<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21c.7-4.2 3.3-6 8-6s7.3 1.8 8 6"/></svg>'};
  const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
  const write=(key,val)=>{localStorage.setItem(key,JSON.stringify(val));document.dispatchEvent(new Event("stepstyle:storage"));};
  const product=id=>window.PRODUCTS.find(p=>p.id===id);
  const money=value=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(value);
  const price=p=>Math.round((p.price*(1-p.discount/100))*100)/100;
  const cart=()=>read(KEYS.cart,[]);
  const wishlist=()=>read(KEYS.wishlist,[]);
  const session=()=>read(KEYS.session,null);
  const cartCount=()=>cart().reduce((s,i)=>s+i.quantity,0);
  const subtotal=()=>cart().reduce((s,i)=>{const p=product(i.id);return p?s+price(p)*i.quantity:s},0);
  function toast(message){let el=document.getElementById("globalToast");if(!el){el=document.createElement("div");el.id="globalToast";el.className="toast";document.body.appendChild(el)}el.textContent=message;el.classList.add("show");clearTimeout(window.__stepToast);window.__stepToast=setTimeout(()=>el.classList.remove("show"),2100)}
  function header(){const s=session();return `<div class="utility-bar"><div class="shell utility-inner"><span>Envío gratis en compras mayores a $2,500</span><div class="utility-links"><a href="index.html#help">Ayuda</a>${s?`<a href="perfil.html">${s.name}</a><button data-logout>Cerrar sesión</button>`:`<a href="registro.html">Únete</a><a href="login.html">Iniciar sesión</a>`}</div></div></div><header class="header" id="header"><div class="shell nav-row"><button class="menu-button icon-button" data-menu aria-label="Abrir menú">${icons.menu}</button><a class="wordmark" href="index.html">STEP<span>STYLE</span></a><nav class="desktop-nav"><a href="index.html?filter=Novedades#products">Novedades</a><a href="index.html?filter=Hombre#products">Hombre</a><a href="index.html?filter=Mujer#products">Mujer</a><a href="index.html?category=Tenis#products">Tenis</a><a href="index.html?category=Botines#products">Botines</a><a class="sale-link" href="index.html?filter=Ofertas#products">Ofertas</a></nav><div class="nav-actions"><a class="icon-button" href="favoritos.html" aria-label="Favoritos">${icons.heart}<span class="count" id="wishlistCount">0</span></a><button class="icon-button" data-cart-drawer aria-label="Carrito">${icons.bag}<span class="count" id="cartCount">0</span></button><a class="icon-button account-icon" href="${s?'perfil.html':'login.html'}" aria-label="Cuenta">${icons.user}</a></div></div><nav class="mobile-nav" data-mobile-nav><a href="index.html?filter=Novedades#products">Novedades</a><a href="index.html?filter=Hombre#products">Hombre</a><a href="index.html?filter=Mujer#products">Mujer</a><a href="index.html?category=Tenis#products">Tenis</a><a href="index.html?category=Zapatos#products">Zapatos</a><a href="index.html?category=Botines#products">Botines</a><a href="index.html?category=Sandalias#products">Sandalias</a><a href="index.html?filter=Ofertas#products">Ofertas</a></nav></header>`}
  function footer(){return `<footer class="footer"><div class="shell footer-grid"><div class="footer-brand-block"><a class="wordmark footer-wordmark" href="index.html">STEP<span>STYLE</span></a><p>Calzado moderno, cómodo y fácil de comprar.</p></div><div><h3>Productos</h3><a href="index.html?filter=Novedades#products">Novedades</a><a href="index.html?filter=Hombre#products">Hombre</a><a href="index.html?filter=Mujer#products">Mujer</a><a href="index.html?filter=Ofertas#products">Ofertas</a></div><div><h3>Ayuda</h3><a href="index.html#help">Envíos</a><a href="index.html#help">Cambios y devoluciones</a><a href="index.html#help">Contacto</a><a href="index.html#help">Preguntas frecuentes</a></div><div><h3>Tu cuenta</h3><a href="favoritos.html">Favoritos</a><a href="carrito.html">Carrito</a><a href="perfil.html">Perfil</a></div></div><div class="shell footer-bottom"><span>© 2026 StepStyle. Proyecto académico.</span><span>México · MXN</span></div></footer>`}
  function updateCounters(){const c=document.getElementById("cartCount"),w=document.getElementById("wishlistCount");if(c)c.textContent=cartCount();if(w)w.textContent=wishlist().length}
  function renderDrawer(){const drawer=document.getElementById("globalCartDrawer");if(!drawer)return;const c=cart();const items=drawer.querySelector("[data-drawer-items]");drawer.querySelector("[data-drawer-subtotal]").textContent=money(subtotal());items.innerHTML=c.length?c.map((i,idx)=>{const p=product(i.id);return `<div class="drawer-item"><img src="${p.image}" alt="${p.name}"><div><strong>${p.name}</strong><small>Talla ${i.size} · ${i.color}<br>Cantidad ${i.quantity}</small><b>${money(price(p)*i.quantity)}</b><button data-drawer-remove="${idx}">Eliminar</button></div></div>`}).join(""):`<div class="drawer-empty">Tu carrito está vacío.</div>`}
  function openDrawer(){renderDrawer();document.getElementById("globalCartDrawer")?.classList.add("open");document.getElementById("globalCartBackdrop")?.classList.add("show")}
  function closeDrawer(){document.getElementById("globalCartDrawer")?.classList.remove("open");document.getElementById("globalCartBackdrop")?.classList.remove("show")}
  function initLayout(){const h=document.getElementById("siteHeader"),f=document.getElementById("siteFooter");if(h)h.innerHTML=header();if(f)f.innerHTML=footer();document.body.insertAdjacentHTML("beforeend",`<div class="cart-backdrop" id="globalCartBackdrop"></div><aside class="cart-drawer" id="globalCartDrawer" aria-label="Carrito lateral"><div class="drawer-top"><h2>Tu carrito</h2><button data-drawer-close aria-label="Cerrar">×</button></div><div class="drawer-items" data-drawer-items></div><div class="drawer-bottom"><div><span>Subtotal</span><strong data-drawer-subtotal>${money(0)}</strong></div><a class="button button-dark full-width" href="carrito.html">Ver carrito</a></div></aside>`);updateCounters();renderDrawer();document.querySelector("[data-menu]")?.addEventListener("click",()=>document.querySelector("[data-mobile-nav]")?.classList.toggle("open"));document.querySelector("[data-cart-drawer]")?.addEventListener("click",openDrawer);document.querySelector("[data-drawer-close]")?.addEventListener("click",closeDrawer);document.getElementById("globalCartBackdrop")?.addEventListener("click",closeDrawer);document.getElementById("globalCartDrawer")?.addEventListener("click",e=>{const b=e.target.closest("[data-drawer-remove]");if(!b)return;const c=cart();c.splice(Number(b.dataset.drawerRemove),1);setCart(c);renderDrawer()});document.querySelectorAll("[data-logout]").forEach(b=>b.addEventListener("click",()=>{localStorage.removeItem(KEYS.session);location.href="index.html"}));document.addEventListener("stepstyle:storage",()=>{updateCounters();renderDrawer()});window.addEventListener("storage",()=>{updateCounters();renderDrawer()})}
  function addCart(id,{size,color,quantity=1}={}){const p=product(id);if(!p)return;let c=cart();size=size??p.sizes[0];color=color??p.colors[0];let existing=c.find(i=>i.id===id&&String(i.size)===String(size)&&i.color===color);const already=existing?existing.quantity:0;if(already+quantity>p.stock){toast("No hay suficiente stock disponible");return false}if(existing)existing.quantity+=quantity;else c.push({id,size,color,quantity});write(KEYS.cart,c);toast(`${p.name} agregado a la bolsa`);return true}
  function setCart(c){write(KEYS.cart,c)}
  function toggleWishlist(id){let w=wishlist();if(w.includes(id)){w=w.filter(x=>x!==id);toast("Producto eliminado de favoritos")}else{w.push(id);toast("Producto guardado en favoritos")}write(KEYS.wishlist,w);return w.includes(id)}
  function requireLogin(){if(!session()){sessionStorage.setItem("stepstyle_redirect","checkout.html");location.href="login.html?required=1";return false}return true}
  function shippingByZip(zip,sub){if(sub>=2500)return 0;if(!/^\d{5}$/.test(zip))return null;const n=Number(zip);if(n>=88000&&n<=88999)return 99;if((n>=64000&&n<=64999)||(n>=44000&&n<=44999))return 129;return 169}
  function coupon(code,sub){const normalized=(code||"").trim().toUpperCase();if(normalized==="PROFE100")return {code:normalized,label:"$100 de descuento",amount:Math.min(100,sub)};if(normalized==="STEP20")return {code:normalized,label:"20% de descuento",amount:sub*.20};return null}
  return {KEYS,icons,read,write,product,money,price,cart,wishlist,session,subtotal,toast,initLayout,updateCounters,addCart,setCart,toggleWishlist,requireLogin,shippingByZip,coupon};
})();
document.addEventListener("DOMContentLoaded",()=>StepStyle.initLayout());